services:
  mic_interface:
    image: arnyminerz/mic_manager:development
  radicale:
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
