version: '3.7'

services:
  mic_interface:
    image: arnyminerz/mic_manager:development
    container_name: mic_interface
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - mariadb
      - radicale
      - firefly
    environment:
      - DEBUG=true
      - DB_USERNAME
      - DB_DATABASE
      - DB_HOSTNAME=mariadb
      - PRIVATE_KEY_FILE=/run/secrets/private_key
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - CALDAV_HOSTNAME=radicale
      - CALDAV_SSL_ENABLE=false
      - CALDAV_PORT=5232
      - CALDAV_USERNAME
      - CALDAV_PASSWORD
      - CALDAV_AB_UUID
      - FIREFLY_HOST=${FIREFLY_HOST:-firefly}
      - FIREFLY_PORT=${FIREFLY_PORT:-8080}
      - FIREFLY_TOKEN_FILE=/run/secrets/firefly_token
      - STRIPE_SECRET
      # Enable props when necessary
      # - PROPS=migration
      - PROPS
    ports:
      - '3000:3000'
    secrets:
      - db_password
      - private_key
      - firefly_token
    volumes:
      - server-keys:/usr/src/app/keys

  mariadb:
    image: linuxserver/mariadb
    container_name: mic_mariadb
    restart: unless-stopped
    # TODO: Remove, just for testing
    ports:
      - "3306:3306"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}

      - FILE__MYSQL_PASSWORD=/run/secrets/db_password
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    volumes:
      - ./.docker/mariadb/config:/config
    networks:
      - backend

  radicale:
    image: tomsquest/docker-radicale
    container_name: mic_radicale
    restart: unless-stopped
    ports:
      - "5232:5232"
    networks:
      - backend
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    healthcheck:
      test: curl -f http://localhost:5232 || exit 1
      interval: 30s
      retries: 3
    volumes:
      - ./.docker/radicale:/data
      - ./radicale-config:/config:ro

  firefly:
    image: fireflyiii/core
    container_name: mic_firefly
    restart: unless-stopped
    depends_on:
      - firefly_db
      - firefly_cache
    # TODO: Disable exposing ports
    ports:
      - "8080:8080"
    networks:
      - backend
      - firefly
    env_file: firefly.env
    environment:
      - APP_KEY_FILE=/run/secrets/firefly_app_key
      - DB_HOST=firefly_db
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD_FILE=/run/secrets/firefly_db_password
      - REDIS_PASSWORD=SRGjFe44zo4UaTqFm7UcZ6pcqeRG9PRw
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    secrets:
      - firefly_app_key
      - firefly_db_password
  firefly_db:
    image: mariadb
    container_name: mic_firefly_db
    restart: unless-stopped
    networks:
      - firefly
    environment:
      - MARIADB_USER=firefly
      - MARIADB_DATABASE=firefly

      - MARIADB_PASSWORD_FILE=/run/secrets/firefly_db_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/firefly_db_root_password
    volumes:
      - firefly_iii_db:/var/lib/mysql
    secrets:
      - firefly_db_password
      - firefly_db_root_password
  firefly_cache:
    image: redis:6.2-alpine
    container_name: mic_firefly_cache
    restart: unless-stopped
    networks:
      - firefly
    command: redis-server --save 20 1 --loglevel warning --requirepass SRGjFe44zo4UaTqFm7UcZ6pcqeRG9PRw
    volumes:
      - firefly_iii_cache:/data

networks:
  backend:
    driver: bridge
  firefly:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
  server-keys:
    driver: local
  firefly_iii_upload:
  firefly_iii_db:
  firefly_iii_cache:
    driver: local

secrets:
  db_username:
    file: ./secrets/username.txt
  db_password:
    file: ./secrets/password.txt
  db_root_password:
    file: ./secrets/root-password.txt
  db_database:
    file: ./secrets/database.txt
  private_key:
    file: ./secrets/private.key
  firefly_db_password:
    file: ./secrets/firefly-password.txt
  firefly_db_root_password:
    file: ./secrets/firefly-root-password.txt
  firefly_app_key:
    file: ./secrets/firefly-app-key.txt
  firefly_token:
    file: ./secrets/firefly-token.txt
