name: "Test"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  prepare:
    name: 'Prepare environment'
    uses: ./.github/workflows/prepare.yml
  test:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - name: Tests
        run: npm test
        env:
          DEBUG: testcontainers:containers  # Enable container logging
          PROPS: testing                    # Enable testing props
  report:
    name: 'Create Tests Report'
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - name: Run Report
        run: npm run ci
        env:
          PROPS: testing
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Mocha Tests           # Name of the check run which will be created
          path: test-*.json           # Path to test results
          reporter: mocha-json        # Format of test results
